### ISSUE TITLE
[JOSS Review] Add more descriptive function names to unit tests

### ISSUE THREAD

**Issue by sea-bass** [auctus-team/pycapacity#7]
Right now, all the unit test functions are named `test1()`, `test2()`, etc. which is not very descriptive.

Consider more readable names that communicate the purpose of the test, for example `test_invalid_polytope_x_min()`.

https://github.com/openjournals/joss-reviews/issues/5670

**Comment by askuric** [comment]
Thanks for the feedback, I've updated the function names. I was trying to be as descriptive as possible in the comments, but I agree that the redundancy improves the clarity. :D
Thanks!

**Comment by sea-bass** [comment]
Thank you! Looks good.
